import { simulation } from "../src/engine.js";
import { addInventory } from "../src/economy/inventory.js";
import { CONTENT } from "../src/content/index.js";
const state = simulation.createInitialState();
addInventory(state, "town", "wood", 600, "t", "test", CONTENT);
const built = simulation.buildAt(state, "mill", "east");
simulation.advanceDays(state, 40);
const mill = state.buildings[0];
console.log("mill:", JSON.stringify(mill, null, 1).slice(0, 800));
console.log("business.buildings keys:", Object.keys(state.business.buildings));
simulation.setEmployment(state, `${mill.id}::millers`, 4);
console.log("after setEmployment, keys:", Object.keys(state.business.buildings));
console.log("jobCount:", (await import("../src/systems/households.js")).jobCount(state, `${mill.id}::millers`));
addInventory(state, "town", "wood", 600, "t2", "test", CONTENT);
const up = simulation.upgradeBuilding(state, mill.id);
console.log("upgrade:", JSON.stringify(up).slice(0,300));
console.log("keys after upgrade:", Object.keys(state.business.buildings));
simulation.advanceDay(state);
console.log("keys after day:", Object.keys(state.business.buildings));
for (const [k,v] of Object.entries(state.business.buildings)) console.log(k, JSON.stringify(v));
console.log("mill.typeId", mill.typeId, "level", mill.level);
console.log("town wheat", state.accounts.town.wheat, "town flour", state.accounts.town.flour);
