import { simulation } from "../src/engine.js";
import { addInventory } from "../src/economy/inventory.js";
import { CONTENT } from "../src/content/index.js";
import { jobCount } from "../src/systems/households.js";

const state = simulation.createInitialState();
addInventory(state, "town", "wood", 600, "t", "test", CONTENT);
simulation.buildAt(state, "mill", "east");
simulation.advanceDays(state, 40);
const mill = state.buildings[0];
simulation.setEmployment(state, `${mill.id}::millers`, 4);
console.log("buildings:", state.buildings.map(b => b.typeId + ":" + b.id).join(", "));
console.log("has wholesale?", !!state.wholesale);
console.log("wholesale:", state.wholesale ? JSON.stringify({ inv: state.wholesale.inventory, mono: Object.keys(state.wholesale) }) : "NONE");
const before = state.accounts.town.wheat;
simulation.advanceDay(state);
console.log("wheat", before, "->", state.accounts.town.wheat);
console.log("flour town:", state.accounts.town.flour);
console.log("wholesale inv after:", state.wholesale ? JSON.stringify(state.wholesale.inventory) : "NONE");
console.log("buildings now:", state.buildings.map(b => b.typeId).join(", "));
console.log("producedUnits:", JSON.stringify(state.business.day.producedUnits));
console.log("last 8 events:", state.events.slice(-8).map(e => e.message).join(" || "));
